version: '3'

services:
  database:
    image: drupaldocker/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: meh
    ports:
      - "9906:3306"
  web:
    image: aprice42/drupalphp:latest
    container_name: drupal_web
    links:
      - database
    volumes:
    # set ./app to name of root directory containing project files
      - ./app:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
